<?php
/**
 * @file
 * immunizationed_practice_inputs.features.og_features_permission.inc
 */

/**
 * Implements hook_og_features_default_permissions().
 */
function immunizationed_practice_inputs_og_features_default_permissions() {
  $permissions = array();

  // Exported og permission: 'node:practice_admin_group:create convenient_vaccination_services content'
  $permissions['node:practice_admin_group:create convenient_vaccination_services content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_admin_group:create enhanced_vaccination_systems content'
  $permissions['node:practice_admin_group:create enhanced_vaccination_systems content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_admin_group:create meeting_agenda content'
  $permissions['node:practice_admin_group:create meeting_agenda content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_admin_group:create motivation content'
  $permissions['node:practice_admin_group:create motivation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_admin_group:create patient_notification content'
  $permissions['node:practice_admin_group:create patient_notification content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_admin_group:delete any convenient_vaccination_services content'
  $permissions['node:practice_admin_group:delete any convenient_vaccination_services content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:create convenient_vaccination_services content'
  $permissions['node:practice_group:create convenient_vaccination_services content'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:create enhanced_vaccination_systems content'
  $permissions['node:practice_group:create enhanced_vaccination_systems content'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:create meeting_agenda content'
  $permissions['node:practice_group:create meeting_agenda content'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:create motivation content'
  $permissions['node:practice_group:create motivation content'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:create patient_notification content'
  $permissions['node:practice_group:create patient_notification content'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:delete any convenient_vaccination_services content'
  $permissions['node:practice_group:delete any convenient_vaccination_services content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:delete any enhanced_vaccination_systems content'
  $permissions['node:practice_group:delete any enhanced_vaccination_systems content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:delete any meeting_agenda content'
  $permissions['node:practice_group:delete any meeting_agenda content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:delete any motivation content'
  $permissions['node:practice_group:delete any motivation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:delete any patient_notification content'
  $permissions['node:practice_group:delete any patient_notification content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:delete own convenient_vaccination_services content'
  $permissions['node:practice_group:delete own convenient_vaccination_services content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:delete own enhanced_vaccination_systems content'
  $permissions['node:practice_group:delete own enhanced_vaccination_systems content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:delete own meeting_agenda content'
  $permissions['node:practice_group:delete own meeting_agenda content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:delete own motivation content'
  $permissions['node:practice_group:delete own motivation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:delete own patient_notification content'
  $permissions['node:practice_group:delete own patient_notification content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:update any convenient_vaccination_services content'
  $permissions['node:practice_group:update any convenient_vaccination_services content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:update any enhanced_vaccination_systems content'
  $permissions['node:practice_group:update any enhanced_vaccination_systems content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:update any meeting_agenda content'
  $permissions['node:practice_group:update any meeting_agenda content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:update any motivation content'
  $permissions['node:practice_group:update any motivation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:update any patient_notification content'
  $permissions['node:practice_group:update any patient_notification content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:update field_assembly_instruction field'
  $permissions['node:practice_group:update field_assembly_instruction field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update field_assembly_instruction_p2 field'
  $permissions['node:practice_group:update field_assembly_instruction_p2 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update field_assembly_instruction_p3 field'
  $permissions['node:practice_group:update field_assembly_instruction_p3 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update field_assembly_instruction_p4 field'
  $permissions['node:practice_group:update field_assembly_instruction_p4 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update field_date field'
  $permissions['node:practice_group:update field_date field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update field_date_started field'
  $permissions['node:practice_group:update field_date_started field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update field_date_task_completed field'
  $permissions['node:practice_group:update field_date_task_completed field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update field_next_meeting_date field'
  $permissions['node:practice_group:update field_next_meeting_date field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update field_notes field'
  $permissions['node:practice_group:update field_notes field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update field_other_please_specify_p1 field'
  $permissions['node:practice_group:update field_other_please_specify_p1 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update field_other_please_specify_p2 field'
  $permissions['node:practice_group:update field_other_please_specify_p2 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update field_other_please_specify_p3 field'
  $permissions['node:practice_group:update field_other_please_specify_p3 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update field_other_please_specify_p4 field'
  $permissions['node:practice_group:update field_other_please_specify_p4 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update field_req_assembly_instruc_p1 field'
  $permissions['node:practice_group:update field_req_assembly_instruc_p1 field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:update field_req_assembly_instruc_p2 field'
  $permissions['node:practice_group:update field_req_assembly_instruc_p2 field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:update field_req_assembly_instruc_p3 field'
  $permissions['node:practice_group:update field_req_assembly_instruc_p3 field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:update field_req_assembly_instruc_p4 field'
  $permissions['node:practice_group:update field_req_assembly_instruc_p4 field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:update field_task_due_date field'
  $permissions['node:practice_group:update field_task_due_date field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:practice_group:update field_task_start_date field'
  $permissions['node:practice_group:update field_task_start_date field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update own convenient_vaccination_services content'
  $permissions['node:practice_group:update own convenient_vaccination_services content'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update own enhanced_vaccination_systems content'
  $permissions['node:practice_group:update own enhanced_vaccination_systems content'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update own meeting_agenda content'
  $permissions['node:practice_group:update own meeting_agenda content'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update own motivation content'
  $permissions['node:practice_group:update own motivation content'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:update own patient_notification content'
  $permissions['node:practice_group:update own patient_notification content'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_assembly_instruction field'
  $permissions['node:practice_group:view field_assembly_instruction field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_assembly_instruction_p2 field'
  $permissions['node:practice_group:view field_assembly_instruction_p2 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_assembly_instruction_p3 field'
  $permissions['node:practice_group:view field_assembly_instruction_p3 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_assembly_instruction_p4 field'
  $permissions['node:practice_group:view field_assembly_instruction_p4 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_date field'
  $permissions['node:practice_group:view field_date field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_date_started field'
  $permissions['node:practice_group:view field_date_started field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_date_task_completed field'
  $permissions['node:practice_group:view field_date_task_completed field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_epic_id field'
  $permissions['node:practice_group:view field_epic_id field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_next_meeting_date field'
  $permissions['node:practice_group:view field_next_meeting_date field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_notes field'
  $permissions['node:practice_group:view field_notes field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_other_please_specify_p1 field'
  $permissions['node:practice_group:view field_other_please_specify_p1 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_other_please_specify_p2 field'
  $permissions['node:practice_group:view field_other_please_specify_p2 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_other_please_specify_p3 field'
  $permissions['node:practice_group:view field_other_please_specify_p3 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_other_please_specify_p4 field'
  $permissions['node:practice_group:view field_other_please_specify_p4 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_req_assembly_instruc_p1 field'
  $permissions['node:practice_group:view field_req_assembly_instruc_p1 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_req_assembly_instruc_p2 field'
  $permissions['node:practice_group:view field_req_assembly_instruc_p2 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_req_assembly_instruc_p3 field'
  $permissions['node:practice_group:view field_req_assembly_instruc_p3 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_req_assembly_instruc_p4 field'
  $permissions['node:practice_group:view field_req_assembly_instruc_p4 field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_task_due_date field'
  $permissions['node:practice_group:view field_task_due_date field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:practice_group:view field_task_start_date field'
  $permissions['node:practice_group:view field_task_start_date field'] = array(
    'roles' => array(
      'Administrator member' => 'Administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  return $permissions;
}
